# -*- coding: utf-8 -*-
"""ds_practical_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12-ogXKUOm_N-_FV09k1nviAsUHliS3Qh
"""

import numpy as np
import pandas as pd

df = pd.read_csv('datasets/iris.csv')
df.head()

df.shape

# Load the Iris dataset
df2 = pd.read_csv('datasets/StudentsPerformance.csv')

# Define the numeric variable and the categorical variable
numeric_variable = 'math score'
categorical_variable = 'gender'

# Calculate summary statistics grouped by the categorical variable
summary_stats = df2.groupby(categorical_variable)[numeric_variable].describe()

# Print the summary statistics
print(summary_stats)

# Question 2
# Filter the dataset for the specified species
# species_to_analyze = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
# filtered_df = df[df['species'].isin(species_to_analyze)]

# Calculate basic statistical details for each species
species_stats = df.groupby('species').describe()

# Print the statistical details
print(species_stats)

# Calculate percentile for each species
species_percentile_1 = df.groupby('species')['sepal_length'].quantile([0.25, 0.5, 0.75])
species_percentile_2 = df.groupby('species')['sepal_width'].quantile([0.25, 0.5, 0.75])
species_percentile_3 = df.groupby('species')['petal_length'].quantile([0.25, 0.5, 0.75])
species_percentile_4 = df.groupby('species')['petal_width'].quantile([0.25, 0.5, 0.75])

# Print the percentile for each species
print(species_percentile_1)
print(species_percentile_2)
print(species_percentile_3)
print(species_percentile_4)