# -*- coding: utf-8 -*-
"""ds_practical_08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uw4es2XDojb16W0-um7W3414mWh3Op8Z
"""

import seaborn as sns
import matplotlib.pyplot as plt
from seaborn import load_dataset

# Load the Titanic dataset
titanic = load_dataset('titanic')

# Task 1: Explore patterns in the data using Seaborn
# Pairplot to visualize relationships between numerical variables
sns.pairplot(titanic)
plt.title('Pairplot of Titanic Dataset')
plt.show()

titanic.head()

# Task 2: Plot a histogram to visualize the distribution of ticket prices
plt.figure(figsize=(10, 6))
sns.histplot(data=titanic, x='fare', bins=30, kde=True)
plt.title('Distribution of Ticket Prices')
plt.xlabel('Fare')
plt.ylabel('Frequency')
plt.show()

sns.scatterplot(data=titanic, x=titanic['fare'], y=titanic['age'])
# Defining a scatterplot to understand Fare vs Age factors. AKA: What person with age "X" paid "Y" price.

sns.lineplot(data=titanic, x=titanic['survived'], y=titanic['age'])

sns.barplot(data=titanic, x="embarked", y="survived")

sns.scatterplot(titanic)
plt.title('Pairplot of Titanic Dataset')
plt.show()

sns.countplot(x=titanic['sex'], hue=titanic['survived'])