# -*- coding: utf-8 -*-
"""ds_practical_09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H1852bGxfOIKWXFmPcMpzTr34tLQ-Dxe
"""

import seaborn as sns
import matplotlib.pyplot as plt
from seaborn import load_dataset

# Load the Titanic dataset
titanic = load_dataset('titanic')

# Plot a box plot for distribution of age with respect to gender and survival status
plt.figure(figsize=(5, 3))
sns.boxplot(data=titanic, x='sex', y='age', hue='survived')
plt.title('Distribution of Age by Gender and Survival Status')
plt.xlabel('Gender')
plt.ylabel('Age')
plt.legend(title='Survived', loc='upper right', labels=['No', 'Yes'])
plt.show()