# -*- coding: utf-8 -*-
"""ds_practical_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iom6NPpZhjwqM8NhkA5Foj6G8hs1siFb
"""

# Question 1
import numpy as np
import pandas as pd

# Question 2, 3

df = pd.read_csv('datasets/titanic.csv')

df.head()

# Question 4
df.describe()

df.isna().sum()

df.isnull()

df.isnull().value_counts()

df.info()

size = df.size
shape = df.shape

print(f"Size of dataframe is: {size}\nShape of dataframe is: {shape}")

# Question 5

# Step 1: Check data types of variables
data_types_summary = df.dtypes
print("Data Types Summary:")
print(data_types_summary)

# Convert 'Pclass' to categorical variable
df['Pclass'] = df['Pclass'].astype('category')

# Convert 'Age' to numeric (assuming it's stored as object/string)
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

# Convert 'Age' to integer
df['Age'] = df['Age'].astype(int)

# Now, let's check the data types after conversion
print("\nData Types after Conversion:")
print(df.dtypes)

# Question 6

# Step 3: Perform one-hot encoding
# Let's say we want to encode the 'Sex' and 'Embarked' columns
# We'll use pd.get_dummies() to create binary columns for each category

# Perform one-hot encoding for 'Sex' column
sex_dummies = pd.get_dummies(df['Sex'], prefix='Sex')

# Perform one-hot encoding for 'Embarked' column
embarked_dummies = pd.get_dummies(df['Embarked'], prefix='Embarked')

# Concatenate the original DataFrame with the one-hot encoded columns
df_encoded = pd.concat([df, sex_dummies, embarked_dummies], axis=1)

# Drop the original categorical columns from the DataFrame
df_encoded.drop(['Sex', 'Embarked'], axis=1, inplace=True)

# Now, 'Sex' and 'Embarked' have been transformed into quantitative variables using one-hot encoding
# The new columns represent each category with binary values (0 or 1)

df.head

